### ISSUE TITLE
[Bug]: Wrong Table Column Name

### ISSUE THREAD

**Issue by akm2121** [SaiWunnaAung/group4#68]
### What happened?

This bug is about the wrong table column name. The wrong name is "Continent" which should be replace with "Country". Because the output code is about the Country Data and not the continent data. 

![bug1 1](https://user-images.githubusercontent.com/101541319/162250253-6168d69c-71a8-4689-a3d5-f872df80df21.PNG)
 

### Sprint

Sprint-4

### Bug Type

Report Output

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaiWunnaAung** [comment]
I already fix this error you can check below figure
![fix1](https://user-images.githubusercontent.com/101235880/162355833-e861a98d-03be-4b25-aba1-004306110aff.PNG)
.
