### ISSUE TITLE
[Bug]: Code Quality issues

### ISSUE THREAD

**Issue by akm2121** [SaiWunnaAung/group4#70]
### What happened?

This project include a lot of codes. So some of the code should be comment about how they will perform. Adding comment about code is also include in code quality metric and it can improve the code quality of the project. The code quality is important and it can impacts the overall software quality in quality impacts such as how safe, secure, and reliable the codebase is.

![bug3 1](https://user-images.githubusercontent.com/101541319/162252261-daea662b-d492-4930-af81-af68d0ec10ed.png)

### Sprint

Sprint-4

### Bug Type

Code Quality

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaiWunnaAung** [comment]
I already fix this bug you can check in below fingure

![sdfdf.PNG](https://zube.io/files/group4-2/76644257ce5b146d80c20c4635318cb1-sdfdf.png)
