### ISSUE TITLE
[Bug]: Data Output Problem

### ISSUE THREAD

**Issue by akm2121** [SaiWunnaAung/group4#72]
### What happened?

The bug is related to the report output. The problem is that some of the table attributes are not necessary in this kind of report. for example some of the field has no value. 
For the better output format, these kind of attribute should be removed from the table.

![bug4 1](https://user-images.githubusercontent.com/101541319/162254322-50a3913e-3cc2-488c-a35d-11ad1dde1bd8.png)

### Sprint

Sprint-4

### Bug Type

Report Output

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaiWunnaAung** [comment]
I will fix this error on sprint 5.
